# Generated by Django 3.2.9 on 2021-11-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblfop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.IntegerField(blank=True, db_column='RECORD', null=True, unique=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=255, null=True)),
                ('stan', models.CharField(blank=True, db_column='STAN', max_length=30, null=True)),
                ('activity_kinds', models.TextField(blank=True, db_column='ACTIVITY_KINDS', null=True)),
                ('registration', models.DateField(blank=True, db_column='REGISTRATION', null=True)),
                ('exchange_data', models.TextField(blank=True, db_column='EXCHANGE_DATA', null=True)),
                ('current_authority', models.CharField(blank=True, db_column='CURRENT_AUTHORITY', max_length=255, null=True)),
                ('other_contact', models.CharField(blank=True, db_column='OTHER_CONTACT', max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, db_column='CONTACT_EMAIL', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblFOP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbluo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.IntegerField(blank=True, db_column='RECORD', null=True, unique=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=300, null=True)),
                ('short_name', models.CharField(blank=True, db_column='SHORT_NAME', max_length=255, null=True)),
                ('opf', models.CharField(blank=True, db_column='OPF', max_length=255, null=True)),
                ('edrpou', models.IntegerField(blank=True, db_column='EDRPOU', null=True)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=255, null=True)),
                ('stan', models.CharField(blank=True, db_column='STAN', max_length=30, null=True)),
                ('activity_kinds', models.TextField(blank=True, db_column='ACTIVITY_KINDS', null=True)),
                ('registration', models.DateField(blank=True, db_column='REGISTRATION', null=True)),
                ('other_contact', models.CharField(blank=True, db_column='OTHER_CONTACT', max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, db_column='CONTACT_EMAIL', max_length=255, null=True)),
                ('exchange_data', models.TextField(blank=True, db_column='EXCHANGE_DATA', null=True)),
                ('founders', models.TextField(blank=True, db_column='FOUNDERS', null=True)),
                ('beneficiaries', models.TextField(blank=True, db_column='BENEFICIARIES', null=True)),
                ('signers', models.TextField(blank=True, db_column='SIGNERS', null=True)),
                ('authorized_capital', models.CharField(blank=True, db_column='AUTHORIZED_CAPITAL', max_length=30, null=True)),
                ('statute', models.TextField(blank=True, db_column='STATUTE', null=True)),
                ('current_authority', models.TextField(blank=True, db_column='CURRENT_AUTHORITY', null=True)),
            ],
            options={
                'db_table': 'tblUO',
                'managed': False,
            },
        ),
    ]
